### ISSUE TITLE
100% coverage

### ISSUE THREAD

**Issue by guillaumearm** [guillaumearm/handle-io#72]
https://codecov.io/gh/guillaumearm/handle-io/src/f6c808211fc128864b9cb51db69afe589e101873/src/internal/BypassHandlerError.js

**Comment by guillaumearm** [comment]
Update codecov.yml file : 

```yml
# This file represents the default values when a customer has not filled them out
coverage:
  status:
    project:
      default:
        target: 100%

    patch:
      project:
        default:
          target: 100%

    changes:
      project:
        default:
          target: 100%

comment: false
```
